services:
  public-site:
    build:
      context: .
      dockerfile: projects/public-site/Dockerfile
    container_name: public_site
    restart: unless-stopped
    ports:
      - "8080:80"

  admin-panel:
    build:
      context: .
      dockerfile: projects/admin-panel/Dockerfile
    container_name: admin_panel
    restart: unless-stopped
    ports:
      - "8081:80"
